server:
  port: 8007
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false

logging:
  file:
    path: ./data/logs/
    name: ${spring.application.name}