func:
  # 存储型xss过滤
  xss-filter:
    enable: true
    url-patterns:
      - /*
  # 重放攻击校验（配合前端传参）
  replay-invalidate:
    enable: false
    token: ${spring.application.name}
    expire-seconds: 60
    url-patterns:
      - /*

datasource:
  mysql:
    mysql01:
      enable: false
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc://localhost:3306/database
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: Hikari-mysql01
        # 最小连接数
        minimum-idle: 5
        # 空闲连接存活最大时间（毫秒）
        idle-timeout: 300000
        # 连接池最大连接数
        maximum-pool-size: 20
        # 连接池返回的连接默认自动提交
        auto-commit: true
        # 池中连接最大生命周期, 0表示无限
        max-lifetime: 1800000
        # 数据库连接超时时间
        connection-timeout: 30000
        # 数据库连接测试sql
        connection-test-query: SELECT 1
  redis:
    redis01:
      enable: false
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 10000
      jedis:
        max-total: 50
        max-wait: 50
        max-idle: 3
        min-idle: 0
        test-on-borrow: true
        test-on-return: true